title: "Energy Modeling Tools"
description: "A hub for open-source energy modeling tools"
baseurl: ""
url: "https://energy-modelling-tools.github.io"

markdown: kramdown
theme: null
remote_theme: energy-modelling-tools/page-template@main

sass:
  style: :compressed
  sass_dir: assets/css/
  load_paths:
    - node_modules/
    - node_modules/@primer/view-components/app/components/

plugins:
  - jekyll-remote-theme
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-octicons

exclude:
  - node_modules
  - vendor
  - script
  - package.json
  - package-lock.json
